name: Elixir CI

on:
  push:
    branches-ignore:
      - 'wip-*'
  pull_request: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.12.3
        otp-version: 22.2
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
